modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="tfcfasttriphammer"
version="1.1.0"
displayName="TFC Fast Trip Hammer"
authors="z1z1y2"
description='''
A TFC addon that boosts Trip Hammer speed by 4x and changes Bladed Axle to a cross-shaped blade.
'''

[[mixins]]
config = "tfcfasttriphammer.mixins.json"

[[dependencies.tfcfasttriphammer]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="BOTH"

[[dependencies.tfcfasttriphammer]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.tfcfasttriphammer]]
modId="tfc"
type="required"
versionRange="[4.1.0,)"
ordering="NONE"
side="BOTH"